php:
  preset: laravel
  version: 8
  disabled:
    - laravel_phpdoc_alignment
    - laravel_phpdoc_order
    - laravel_phpdoc_separation
  finder:
    not-name:
      - index.php
      - server.php
      - "*.blade.php"
      - "_ide_helper.php"
    exclude:
      - "modules"
      - "node_modules"
      - "nova"
      - "nova-components"
      - "storage"
      - "spark"
      - "vendor"
